### ISSUE TITLE
Notice on temporary design of navbar/sidebar

### ISSUE THREAD

**Issue by cjfaeldonea** [jvc1019/Zest#12]
`navbar.php` `sidebar.css` `sidebar.js` `home.css` needs modification. 
The commit e137be667dd28a1fb85a58907caf855898b43e67  is a temporary fix on the UI recommendation, but fixes issue #8 .

For the meantime, kindly add `<?php include('navbar.php'); ?>` inside the `<body>` of your current work. It will be replaced later by `sidebar.php`.

**Comment by Stick1000** [comment]
Might be useful: https://bootstrapious.com/p/bootstrap-sidebar#sidebar-4
