### ISSUE TITLE
Self-extracting installer for easier distribution

### ISSUE THREAD

**Issue by jvc1019** [jvc1019/Zest#87]
Possibly create a user-friendly installer for the web app for convenience.

"exe na nakapack yung project, then pag run extract to htdocs, then add desktop shortcut na nag rurun ng apache and open yung app as browser"
- Janley

**Comment by Stick1000** [comment]
Baka pwede niyo rin kunin na lang yung apache component ng XAMPP para di na rin irequire yung user mag install ng XAMPP.
